
import sys

file_path = r'c:\Users\USER\Desktop\Edu-Manager\iai-update\app\Http\Controllers\Admin\NegociationController.php'

with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

new_lines = []
skip = False
for line in lines:
    if 'public function edit($id)' in line and '//' in line:
        skip = True
        continue
    if skip and 'public function ajouterPaiement' in line:
        # Add the new implementations before adding this line
        new_lines.append("    /**\n")
        new_lines.append("     * Mettre à jour une négociation existante\n")
        new_lines.append("     */\n")
        new_lines.append("    public function update(Request $request, $id)\n")
        new_lines.append("    {\n")
        new_lines.append("        $fraisEtudiant = FraisEtudiant::with(['echeances', 'echeancier'])->findOrFail($id);\n")
        new_lines.append("\n")
        new_lines.append("        // Validation\n")
        new_lines.append("        $request->validate([\n")
        new_lines.append("            'echeances' => 'required|array|min:1',\n")
        new_lines.append("            'echeances.*.id' => 'nullable|exists:echeances,id',\n")
        new_lines.append("            'echeances.*.libelle' => 'required|string',\n")
        new_lines.append("            'echeances.*.montant' => 'required|numeric|min:0',\n")
        new_lines.append("            'echeances.*.date_limite' => 'required|date',\n")
        new_lines.append("            'commentaire' => 'nullable|string',\n")
        new_lines.append("            'bourse_etudiant_id' => 'nullable|exists:bourse_etudiants,id'\n")
        new_lines.append("        ]);\n")
        new_lines.append("\n")
        new_lines.append("        DB::beginTransaction();\n")
        new_lines.append("\n")
        new_lines.append("        try {\n")
        new_lines.append("            // 1. Mettre à jour les informations de base si nécessaire\n")
        new_lines.append("            if ($request->has('bourse_etudiant_id')) {\n")
        new_lines.append("                $fraisEtudiant->bourse_etudiant_id = $request->bourse_etudiant_id;\n")
        new_lines.append("            }\n")
        new_lines.append("            $fraisEtudiant->save();\n")
        new_lines.append("\n")
        new_lines.append("            // 2. Gérer les échéances\n")
        new_lines.append("            $idsRecus = [];\n")
        new_lines.append("            \n")
        new_lines.append("            foreach ($request->echeances as $index => $eData) {\n")
        new_lines.append("                if (isset($eData['id'])) {\n")
        new_lines.append("                    // Mise à jour d'une échéance existante\n")
        new_lines.append("                    $echeance = \App\Models\Echeance::findOrFail($eData['id']);\n")
        new_lines.append("                    \n")
        new_lines.append("                    // Sécurité : on ne modifie pas le montant d'une échéance déjà payée (même partiellement)\n")
        new_lines.append("                    if ($echeance->montant_paye == 0) {\n")
        new_lines.append("                        $echeance->update([\n")
        new_lines.append("                            'libelle' => $eData['libelle'],\n")
        new_lines.append("                            'montant' => $eData['montant'],\n")
        new_lines.append("                            'date_limite' => $eData['date_limite'],\n")
        new_lines.append("                            'ordre' => $index + 1\n")
        new_lines.append("                        ]);\n")
        new_lines.append("                    } else {\n")
        new_lines.append("                        // Pour une échéance payée, on ne peut changer que l'ordre\n")
        new_lines.append("                        $echeance->update(['ordre' => $index + 1]);\n")
        new_lines.append("                    }\n")
        new_lines.append("                    $idsRecus[] = $echeance->id;\n")
        new_lines.append("                } else {\n")
        new_lines.append("                    // Création d'une nouvelle échéance\n")
        new_lines.append("                    $nouvelle = \App\Models\Echeance::create([\n")
        new_lines.append("                        'echeancier_id' => $fraisEtudiant->echeancier->id ?? null,\n")
        new_lines.append("                        'frais_etudiant_id' => $fraisEtudiant->id,\n")
        new_lines.append("                        'libelle' => $eData['libelle'],\n")
        new_lines.append("                        'montant' => $eData['montant'],\n")
        new_lines.append("                        'montant_paye' => 0,\n")
        new_lines.append("                        'date_limite' => $eData['date_limite'],\n")
        new_lines.append("                        'ordre' => $index + 1,\n")
        new_lines.append("                        'statut' => 'en_attente'\n")
        new_lines.append("                    ]);\n")
        new_lines.append("                    $idsRecus[] = $nouvelle->id;\n")
        new_lines.append("                }\n")
        new_lines.append("            }\n")
        new_lines.append("\n")
        new_lines.append("            // 3. Supprimer les échéances qui ne sont plus dans la liste\n")
        new_lines.append("            $echeancesASupprimer = \App\Models\Echeance::where('frais_etudiant_id', $fraisEtudiant->id)\n")
        new_lines.append("                ->whereNotIn('id', $idsRecus)\n")
        new_lines.append("                ->get();\n")
        new_lines.append("\n")
        new_lines.append("            foreach ($echeancesASupprimer as $e) {\n")
        new_lines.append("                if ($e->montant_paye > 0) {\n")
        new_lines.append("                    throw new \\Exception(\"Impossible de supprimer l'échéance \\\"{$e->libelle}\\\" car elle contient des paiements.\");\n")
        new_lines.append("                }\n")
        new_lines.append("                $e->delete();\n")
        new_lines.append("            }\n")
        new_lines.append("\n")
        new_lines.append("            // 4. Mettre à jour le commentaire\n")
        new_lines.append("            if ($fraisEtudiant->echeancier) {\n")
        new_lines.append("                $fraisEtudiant->echeancier->update([\n")
        new_lines.append("                    'commentaire' => $request->commentaire\n")
        new_lines.append("                ]);\n")
        new_lines.append("            }\n")
        new_lines.append("\n")
        new_lines.append("            // 5. Mettre à jour le statut global\n")
        new_lines.append("            $fraisEtudiant->updateStatut();\n")
        new_lines.append("\n")
        new_lines.append("            DB::commit();\n")
        new_lines.append("\n")
        new_lines.append("            return response()->json([\n")
        new_lines.append("                'success' => true,\n")
        new_lines.append("                'message' => 'Négociation mise à jour avec succès',\n")
        new_lines.append("                'data' => $fraisEtudiant->load('echeances')\n")
        new_lines.append("            ]);\n")
        new_lines.append("\n")
        new_lines.append("        } catch (\\Exception $e) {\n")
        new_lines.append("            DB::rollBack();\n")
        new_lines.append("            return response()->json([\n")
        new_lines.append("                'success' => false,\n")
        new_lines.append("                'message' => 'Erreur lors de la mise à jour : ' . $e->getMessage()\n")
        new_lines.append("            ], 500);\n")
        new_lines.append("        }\n")
        new_lines.append("    }\n")
        new_lines.append("\n")
        
        skip = False
    
    if not skip:
        new_lines.append(line)

with open(file_path, 'w', encoding='utf-8') as f:
    f.writelines(new_lines)

print("Replacement successful")
